### ISSUE TITLE
Alignment problems

### ISSUE THREAD

**Issue by 0000marcell** [PragTob/pomodoro_tracker#27]
Hi Tobias, i was working on a pomodoro tracker program i've made then i saw yours and decided to try it out, but i'm having this issue. 
![captura de tela 2014-08-30 as 22 27 36](https://cloud.githubusercontent.com/assets/4584144/4100712/60e7760e-30ae-11e4-93e4-8bb00f4e1906.png)

**Comment by PragTob** [comment]
Hi!

Thanks for trying it out! :-)

That's on shoes 4.0.0 pre1 I presume? If so it's a problem I recently fixed over at shoes4, I'm still running it with shoes3 myself. Should be fixed for 4.0.0pre2 which should be released soon.

Thanks  for the report!
